# Project information
site_name: Dev de ZÃ©ro
site_url: https://petoulemonde.github.io/blog
site_author: Pierre-Etienne Toulemonde
site_description: >-
  Bienvenue sur Dev de ZÃ©ro, un lieu de partage de toutes mes dÃ©couvertes informatiques, data, knowledge management et gestion de projet.

# Copyright
copyright: Copyright &copy; 2025 - 2026 Pierre-Etienne Toulemonde

# Additionnal configuration
extra:
  tags:
    data ğŸ“Š: data
    coding ğŸ§‘â€ğŸ’»: coding
    projet ğŸ“‹: projet
    knowledge ğŸ§ : knowledge
    python ğŸ: python
  social:
    - icon: fontawesome/solid/blog
      link: https://penseecomplexe.substack.com/
    - icon: fontawesome/solid/code
      link: https://petoulemonde.github.io/
    - icon: fontawesome/brands/github
      link: https://github.com/petoulemonde/
    - icon: fontawesome/solid/at
      link: mailto:pierre-etienne.toulemonde@outlook.com

# Configuration
theme:
  name: material
  features:
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    # - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    - navigation.expand
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    # - search.highlight
    # - search.share
    # - search.suggest
    # - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      # primary: indigo # Couleur par dÃ©faut
      accent: indigo
      # accent: indigo # Couleur par dÃ©faut
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  favicon: assets/intelligence-artificielle.png
  logo: assets/intelligence-artificielle.png

markdown_extensions:
  - md_in_html

# Plugins
plugins:
  - blog
  - tags
  - rss:
      pretty_print: true
      use_git: false
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
        datetime_format: "%Y-%m-%d"
        default_timezone: Europe/Paris
      image: https://petoulemonde.github.io/blog/assets/intelligence-artificielle_128-128px.jpg
  - search

# Navigation
nav: 
- Bienvenue ğŸ‘‹: 
  - index.md
  - About me ğŸ‘¨: about.md
  - Mon livre Projet ğŸ“‹: projet/index.md
  - Mon livre Data ğŸ“Š: data/index.md
  - Mon livre Knowledge ğŸ§ : knowledge/index.md
  - Mon livre Informatique ğŸ§‘â€ğŸ’»: coding/index.md
  - Mon blog: blog/

- Projet ğŸ“‹:
  - projet/index.md
  - Plan du livre ğŸ—ºï¸: projet/plan.md
  - Les 5 temps du projet:
    - PrÃ©-projet: 
      - projet/prÃ©projet/index.md
      - Business case: projet/prÃ©projet/business_case.md
    - Cadrage: 
      - projet/cadrage/index.md
      - Note de cadrage: projet/cadrage/note_de_cadrage.md
      - Gap analysis: projet/cadrage/gap_analysis.md
    - Conception: projet/conception.md
    - RÃ©alisation: projet/rÃ©alisation.md
    - Retour d'expÃ©rience: projet/cloture.md

- Data ğŸ“Š:
  - data/index.md
  - Qu'est-ce qu'une data ?: data/Qu'est-ce qu'une data.md

- Knowledge ğŸ§ : 
  - Introduction: knowledge/index.md
  - Plan du livre ğŸ—ºï¸: knowledge/plan.md
  - Pourquoi l'IA n'est pas savoir ?: knowledge/Pourquoi l'IA n'est pas savoir.md
  - Veille ğŸ”­:
    - Pourquoi faire une veille ?: knowledge/Pourquoi faire une veille.md

- Informatique ğŸ§‘â€ğŸ’»:
  - coding/index.md
#  - Cookiecutter-data-science - Un outil ğŸ pour structurer ses projets

- Blog: 
  - blog/index.md
  - Articles par tags: tags.md

- Mon Blog Substack ğŸŒ : https://penseecomplexe.substack.com/