# Project information
site_name: Blog de Pierre-Etienne
site_url: https://petoulemonde.github.io/blog
site_author: Pierre-Etienne Toulemonde
site_description: >-
  Bienvenue sur le Pierre-Etienne, lieu de partage de toutes mes dÃ©couvertes informatiques

# Copyright
copyright: Copyright &copy; 2016 - 2025 Pierre-Etienne Toulemonde

# Configuration
theme:
  name: material
  features:
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    # - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    - navigation.expand
    # - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    # - search.highlight
    # - search.share
    # - search.suggest
    # - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  favicon: assets/intelligence-artificielle.png
  logo: assets/intelligence-artificielle.png

markdown_extensions:
  - md_in_html

# Plugins
plugins:
  - blog
  - rss:
      pretty_print: true
      use_git: false
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
        datetime_format: "%Y-%m-%d"
        default_timezone: Europe/Paris
      image: https://petoulemonde.github.io/blog/assets/intelligence-artificielle_128-128px.jpg
  - search

# Additionnal configuration
extra:
  social:
    - icon: fontawesome/solid/blog
      link: https://penseecomplexe.substack.com/
    - icon: fontawesome/solid/code
      link: https://petoulemonde.github.io/
    - icon: fontawesome/brands/github
      link: https://github.com/petoulemonde/

# Navigation
nav: 
- Accueil: 
  - Bienvenue ðŸ‘‹: index.md
  - About me: about.md
- Gestion de projet:
  - projet/index.md
- Data:
  - data/index.md
- Informatique:
  - coding/index.md
- Blog: blog/index.md